name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  novident_tree_view:
     path: ../

  novident_nodes: ^1.1.6
  flutter_quill: ^11.2.0
  cupertino_icons: ^1.0.8
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
