name: flutter_tree_view
description: "A new Flutter package project."
version: 1.0.0-dev1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.12.0
  collection: ^1.18.0
  equatable: ^2.0.5
  uuid: ^4.5.0
  vector_math: ^2.1.4
  flutter_riverpod: ^2.5.1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
