name: novident_tree_view 
description: "A flexible Novident Flutter library for visualizing hierarchical structures with full control over nodes. It allows you to create customizable trees without rigid architectures."
version: 1.0.0
homepage: https://github.com/Novident/novident-tree-view/
repository: https://github.com/Novident/novident-tree-view/ 
documentation: https://github.com/Novident/novident-tree-view/doc/ 
issue_tracker: https://github.com/Novident/novident-tree-view/issues

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.16.0
  collection: ^1.19.1
  provider: ^6.1.4
  novident_nodes: ^1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
